// PM2 Process Management for AI Employee System
// Usage: pm2 start ecosystem.config.js

module.exports = {
  apps: [
    {
      name: "dashboard",
      script: "python3",
      args: "dashboard.py",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/dashboard.log",
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: "gmail-watcher",
      script: "python3",
      args: "gmail_watcher.py --interval 120",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/gmail_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "linkedin-watcher",
      script: "python3",
      args: "linkedin_watcher.py --interval 300",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/linkedin_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "whatsapp-watcher",
      script: "python3",
      args: "whatsapp_watcher.py --interval 180",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/whatsapp_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "filesystem-watcher",
      script: "python3",
      args: "filesystem_watcher.py",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/filesystem_watcher.log",
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: "approval-watcher",
      script: "python3",
      args: "approval_watcher.py",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/approval_watcher.log",
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: "facebook-watcher",
      script: "python3",
      args: "facebook_watcher.py --interval 300",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/facebook_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "instagram-watcher",
      script: "python3",
      args: "instagram_watcher.py --interval 300",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/instagram_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "twitter-watcher",
      script: "python3",
      args: "twitter_watcher.py --interval 300",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/twitter_watcher.log",
      restart_delay: 10000,
      max_restarts: 5,
    },
    {
      name: "orchestrator",
      script: "python3",
      args: "orchestrator.py",
      cwd: "./AI_Employee_Vault/Watchers",
      interpreter: "none",
      env: {
        VAULT_PATH: "/mnt/d/Ai-Employee/AI_Employee_Vault",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "./logs/orchestrator.log",
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: "web-ui",
      script: "npm",
      args: "run start",
      cwd: "./AI_Employee_Vault/web-ui",
      interpreter: "none",
      env: {
        NEXT_PUBLIC_API_URL: "http://localhost:9000",
        PORT: "3000",
      },
      log_file: "./logs/webui.log",
      restart_delay: 5000,
      max_restarts: 10,
    },
  ],
};
